name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.1.0f1  # ProjectVersion.txt 에 맞게
          targetPlatform: StandaloneWindows64
          buildName: MyGame.exe
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64/
