name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-actions/setup@main
        with:
          version: '2022.3.1f1' # 본인 Unity 버전으로 맞추세요

      - name: Activate Unity (Personal license)
        uses: game-ci/unity-actions/activate@main
        with:
          email: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project (Windows)
        uses: game-ci/unity-actions/build@main
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64/
