name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-actions/.github/actions/setup@main
        with:
          version: '6000.1.0f1'  # 여기에 ProjectVersion.txt 값 입력

      - name: Activate Unity
        uses: game-ci/unity-actions/.github/actions/activate@main
        with:
          email: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-actions/.github/actions/build@main
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64/
