name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v3
        with:
          version: '2022.3.1f1'  # 사용하는 Unity 버전에 맞게 설정

      - name: Activate Unity
        uses: game-ci/unity-actions/activate@v3
        with:
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-actions/build@v3
        with:
          targetPlatform: StandaloneWindows64  # WebGL, Android 등도 가능

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/StandaloneWindows64/  # 빌드된 결과물이 저장된 경로
