name: Unity Build (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.1f1  # 본인 프로젝트에 맞게 Unity 버전 입력

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          email: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Windows
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/StandaloneWindows64/
