name: Build Windows Standalone

on:
  push:
    branches: [main]

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Unity (Windows)
        uses: game-ci/unity-setup@v2
        with:
          version: 2022.3.1f1  # ProjectVersion.txt에 맞춰서 입력

      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        with:
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Build project
        run: |
          "C:/Program Files/Unity/Hub/Editor/2022.3.1f1/Editor/Unity.exe" -quit -batchmode -projectPath ${{ github.workspace }} -buildWindows64Player build/StandaloneWindows64/game.exe -logFile build/build.log

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: build/StandaloneWindows64
