name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: '6000.1.0f1'

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          unitySerial: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64/
